language: go
go:
- 1.8.x
services:
- redis-server
before_install:
- wget https://s3.amazonaws.com/sico-ops/config.travis.json -O controller/config.json
install:
- go get -t ./...
script: go test -test.bench=".*" -v ./...
notifications:
  slack:
    secure: va1EuCFAS/T8eHp32qmN1hX0DzDG2SBnv77UNY4n+gs0Si6DWNODpbj1SioBwpcq7u0wMFJOMLo5WdloeHrmXatEFdBP78bYahiJgO27rv9xH/vSHzsiVrHYyMbuiZz+KJF95Gv5FnuVJ4HBSU7MXnthjOEjHwxdWz5cDP4YXpQXGhW0qxyeraGpO18odklUaSl9yCPY92rQVbFH7gZ+Gn+tPm5h1q+u/0BtrKE7S+hTSakIyBaI6btHSSLYhEnHmRI2PZIeKzU66yPFIcTVOd8Jokp7eMvgjDObSD3aALCkkzMTmx8Pl/ij7FgH+AkP3XoyaiEE30/tWuVBMoc03vws4EPAnO+njojrlS+hkq8H+sSXR4X5N7dYSnt2gHL0INo9xpBL1keNvmPazFBI/BFBaP73ahdAJ0pIRN9J3oaATqFfKw+p0qif7VrZienbHr+ToyVaeq5JxYIFRwZce2uswF/0UVq1z/uMmkdw9H0MMHcV9PSCScECwxQpkBjvm4H9m2DmpequcuvYWJe5XKGSa4GKEW4WZqYQyUutjQFy/W6jW8LM4vioBNYh7mhS8MXiWmg6Nyv/ZgApMZupOiSkA6lDKFPNnistl4OItYzolMfr+5k6SUU+1Gycgt4b+fUEJ40XW2PB8sXjEVHZh5UYrIuuoxuax7PW6cRrt0U=